apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: {{ .Release.Name }}
    tier: {{ .Values.redisapp.tier }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      tier: {{ .Values.redisapp.tier }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        tier: {{ .Values.redisapp.tier }}
    spec:
      containers:
      - name: {{ .Values.redisapp.tier }}
        image: {{ .Values.redisImage.name }}
        ports:
        - containerPort: {{ .Values.redisImage.port }}

