apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress

spec:
  rules:
  - host: laravel.test.dl.com 
    http:
      paths:
      - backend:
          service:
            name: myapp-web
            port:
              number: 80
        pathType: ImplementationSpecific
