apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-vol01
  labels:
    app: {{ .Release.Name }}
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: web-pv-claim
  capacity:
    storage: 1Gi
  hostPath:
    path: "/var/lib/data/vol01"
