apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app.tier }}-pv-claim
  labels:
    app: {{ .Release.Name }}
    tier: {{ .Values.app.tier }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.appStorage }}

