apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-vol02
  labels:
    app: {{ .Release.Name }}
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: {{ .Values.pvc.appns }}
    name: {{ .Values.mysqlDeploy.name }}-pv-claim
  capacity:
    storage: {{ .Values.pvc.storage }}
  hostPath:
    path: "{{ .Values.pvc.mysqlPVPath }}"
