apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mysqlDeploy.name }}-pv-claim
  labels:
    app: {{ .Release.Name }}
    tier: {{ .Values.mysqlDeploy.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}

