apiVersion: v1
kind: Service
metadata:
  name: myapp-mysql
  labels:
    app: {{ .Release.Name }}
    tier: mysql
spec:
  ports:
    - port: {{ .Values.mysqlImage.port }}
  selector:
    app: {{ .Release.Name }}
    tier: mysql
  clusterIP: None

