apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app.name }}-{{ .Values.mysqlDeploy.name }}"
  labels:
    app: {{ .Release.Name }}
    tier: {{ .Values.mysqlDeploy.name }}
spec:
  ports:
    - port: {{ .Values.mysqlImage.port }}
  selector:
    app: {{ .Release.Name }}
    tier: {{ .Values.mysqlDeploy.name }}
  clusterIP: None

